// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zklhwdjtccyeoozslafz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprbGh3ZGp0Y2N5ZW9venNsYWZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MzE4NTIsImV4cCI6MjA3MjEwNzg1Mn0.-JrAeMWItASLadezcy-k2v-cqow_W8UAwWvIcYS-UXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});